# Collection settings
collections:
  md_pages:
    output: true
  galleries: {}
  posts:
    permalink: /:categories/:title
  projects:
    output: true
  publications: {}
  publication_types: {}
  showcases: {}
  filterable_tags: {}

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown
kramdown:
  header_offset: 3
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Prevent from clobbering.
# Netlify CMS assets are created before Jekyll build via Rake build
# task.
keep_files:
  - assets/javascripts/cms.js
  - assets/javascripts/cms.js.map
  - assets/javascripts/js-yaml.min.js
  - assets/javascripts/js-yaml.js
  - assets/stylesheets/cms.css
  - assets/src
  - assets/node_modules
