# Collection settings
collections:
  md_pages:
    output: true
  galleries: {}
  posts:
    permalink: /:categories/:title
  projects:
    output: true
    permalink: /projects/:title
  publications:
    output: true
    permalink: /publications/:title
  publication_types: {}
  showcases: {}
  filterable_tags: {}
  logosets:
      output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: publications
    values:
      layout: publication

# Build settings
markdown: kramdown
kramdown:
  header_offset: 3
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Prevent from clobbering.
# Netlify CMS assets are created before Jekyll build via Rake build
# task.
keep_files:
  - assets/javascripts/netlify-cms.js
  - assets/javascripts/netlify-cms.js.map
  - assets/javascripts/js-yaml.min.js
  - assets/javascripts/js-yaml.js
  - assets/src
  - assets/node_modules
