source: en_GB
destination: _site.en_GB

title: ALKA Wildlife
description: >-
  An NGO which helps identify major threats to species survival and develops,
  plans and implements efficient conservation measures through research of
  endangered species ecology.
url: 'https://en.alkawildlife.eu'
logo: /media/logo.png
lang: en_GB
lang_alternatives:
  - icon: /assets/images/flag_cz.png
    label: Změnit na český jazyk
    title: 'Navštivte českou verzi této stránky: %@'
    url: 'https://www.alkawildlife.eu'
    lang: cs_CZ
author: alka-wildlife
facebook:
  admins: 1133305906
  app_id: 145375228868712
  publisher: 269120446533000
social:
  links:
    - 'https://www.facebook.com/AlkaWildlife'
    - 'https://www.instagram.com/alkawildlife'
    - 'https://www.youtube.com/alkawildlife'
  name: 'ALKA Wildlife, o.p.s.'
google_analytics: UA-57533252-8
