source: cs_CZ
destination: _site.cs_CZ

title: ALKA Wildlife
description: >-
  Nezisková nestátní společnost přispívající objektivním výzkumem
  k efektivní, kvalitní odbornými znalostmi podložené ochraně a péči
  o volně žijící druhy živočichů.
baseurl: ""
url: https://www.alkawildlife.eu
author: alka-wildlife
lang_alternatives:
- lang: en_GB
  label: Switch to English
  title: "Visit an English version of this page: %@"
  url: https://en.alkawildlife.eu
  icon: /assets/images/flag_uk.png

facebook:
  app_id: 145375228868712
  publisher: 269120446533000
  admins: 1133305906
logo: /media/logo.png
social:
  name: ALKA Wildlife, o.p.s.
  links:
    - https://www.facebook.com/AlkaWildlife
lang: cs_CZ
kramdown:
  smart_quotes: 0x0201A,0x02018,0x0201E,0x0201C
